services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - UID=${UID}
      - GID=${GID}
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    volumes:
      - ${CONFIG_DIR}/Nordvpn:/config
    restart: unless-stopped
    networks:
      - vpn
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
      - "9117:9117"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ${CONFIG_DIR}/Jellyfin:/config
      - ${DOWNLOADS_DIR}:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Radarr:/config
      - ${DOWNLOADS_DIR}/Movies:/movies
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  torrent:
    image: linuxserver/qbittorrent:latest
    container_name: torrent
    restart: unless-stopped
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK_SET=022
      - WEBUI_PORT=8080
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - ${CONFIG_DIR}/Qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Sonarr:/config
      - ${DOWNLOADS_DIR}/Shows:/tv
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Lidarr:/config
      - ${DOWNLOADS_DIR}/Music:/music
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    network_mode: "service:nordvpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

networks:
  default:
    driver: bridge
  vpn:
    driver: bridge
